export type Expert = {
  id: string
  name: string
  role: string
  image: string
  bio: string
  experience: string
  specialty: string
  quote: string
  email: string
  credentials: string[]
  education: string
  awards: string
}

export const experts: Expert[] = [
  {
    id: 'michael-brown',
    name: 'Michael Brown',
    role: 'Korporativ mobil xizmat rahbari',
    image: 'https://i.pravatar.cc/900?img=12',
    bio: 'Michael biznes mijozlar uchun uzoq muddatli flot va executive transfer jarayonlarini boshqaradi.',
    experience: '10 yil',
    specialty: 'Korporativ park',
    quote: 'Ishonchli xizmat bu oddiy qo‘shimcha emas, mijoz kutadigan asosiy mezon.',
    email: 'michael@drivora.com',
    credentials: ['Korporativ park eksperti', 'MBA darajasi', 'Yuqori darajadagi ingliz tili'],
    education: 'Korporativ logistika, sotuv operatsiyalari va premium transport boshqaruvi yo‘nalishida tajribaga ega.',
    awards: 'Uzoq muddatli parkni rivojlantirish va mijoz bilan barqaror ishlash bo‘yicha e’tirofga ega.',
  },
  {
    id: 'mia-jane',
    name: 'Mia Jane',
    role: 'Sotuv direktori',
    image: 'https://i.pravatar.cc/900?img=32',
    bio: 'Mia premium rental requests bilan ishlaydi va mijozga aynan mos avtomobilni topishda juda kuchli.',
    experience: '8 yil',
    specialty: 'Premium bronlar',
    quote: 'Har bir ijara birinchi qo‘ng‘iroqdan tortib oxirgi topshirishgacha yengil va qulay bo‘lishi kerak.',
    email: 'mia@drivora.com',
    credentials: ['B toifa haydovchilik guvohnomasi', 'Bakalavr darajasi', 'Erkin ingliz tili'],
    education: 'Biznes boshqaruvi va premium mijozlar bilan ishlashga yo‘naltirilgan bron strategiyasi bo‘yicha tayyorgarlikka ega.',
    awards: '2024-yilning eng yaxshi premium bron maslahatchisi va mijozni ushlab qolish bo‘yicha yuqori natija sohibasi.',
  },
  {
    id: 'margaret-nancy',
    name: 'Margaret Nancy',
    role: 'VIP mijozlar menejeri',
    image: 'https://i.pravatar.cc/900?img=47',
    bio: 'Margaret high-end bookings, airport delivery va private client support bo‘yicha jamoaning asosiy mutaxassisi.',
    experience: '7 yil',
    specialty: 'VIP ijara',
    quote: 'Premium xizmat vaqtni to‘g‘ri ushlash, mayda detallarga e’tibor va xotirjam muloqot orqali quriladi.',
    email: 'margaret@drivora.com',
    credentials: ['VIP mijozlar bilan ishlash', 'Servis yo‘nalishi diplomi', 'Yaxshi ingliz tili'],
    education: 'Mehmondo‘stlik va premium mehmonlar bilan ishlash bo‘yicha amaliy tajribaga ega.',
    awards: 'Eng yaxshi VIP xizmat mutaxassisi va premium yetkazib berish sifati uchun e’tirofga sazovor.',
  },
  {
    id: 'daniel-frost',
    name: 'Daniel Frost',
    role: 'Operatsiyalar nazoratchisi',
    image: 'https://i.pravatar.cc/900?img=59',
    bio: 'Daniel kundalik operatsiyalar, mashina tayyorligi va pickup-return jarayonlarini aniq nazorat qiladi.',
    experience: '9 yil',
    specialty: 'Kundalik operatsiyalar',
    quote: 'Silliq ishlaydigan operatsiya premium xizmatni tabiiy va qulay his qildiradi.',
    email: 'daniel@drivora.com',
    credentials: ['Operatsiyalar yetakchisi', 'Logistika sertifikati', 'B toifa haydovchilik guvohnomasi'],
    education: 'Operatsion tizimlar, transport koordinatsiyasi va park jarayonlarini boshqarish bo‘yicha tajribaga ega.',
    awards: 'Barqaror operatsion sifat va bir kun ichida tayyorlash bo‘yicha e’tirofga ega.',
  },
  {
    id: 'emma-carter',
    name: 'Emma Carter',
    role: 'Brend tajribasi menejeri',
    image: 'https://i.pravatar.cc/900?img=25',
    bio: 'Emma mijozning birinchi taassurotidan boshlab brend bilan aloqasini kuchaytiradigan tajribalarni yaratadi.',
    experience: '6 yil',
    specialty: 'Mijoz tajribasi',
    quote: 'Odamlar haydov tugagandan keyin ham xizmat ularda qanday taassurot qoldirganini eslab yuradi.',
    email: 'emma@drivora.com',
    credentials: ['CX mutaxassisi', 'Brend strategiyasi', 'Yaxshi ingliz tili'],
    education: 'Brend kommunikatsiyasi va mijoz tajribasini loyihalash bo‘yicha tayyorgarlikka ega.',
    awards: 'Mijoz mamnunligi va takroriy bronlar o‘sishi bo‘yicha e’tirofga sazovor.',
  },
  {
    id: 'alex-hayes',
    name: 'Alex Hayes',
    role: 'Sport avtomobil mutaxassisi',
    image: 'https://i.pravatar.cc/900?img=15',
    bio: 'Alex sport va performance segmentidagi avtomobillar bo‘yicha chuqur tavsiya va texnik yo‘l-yo‘riq beradi.',
    experience: '11 yil',
    specialty: 'Sport segment',
    quote: 'Kuchli avtomobil to‘g‘ri haydovchi va to‘g‘ri maqsad bilan uyg‘un bo‘lishi kerak.',
    email: 'alex@drivora.com',
    credentials: ['Performance ekspert', 'Texnik sotuv', 'B toifa haydovchilik guvohnomasi'],
    education: 'Sport avtomobillar savdosi va texnik tavsiyalar berish bo‘yicha katta tajribaga ega.',
    awards: 'Sport segmenti bo‘yicha yetakchilik va eng yaxshi mutaxassis maslahatchi sifatida e’tirof etilgan.',
  },
  {
    id: 'sofia-reed',
    name: 'Sofia Reed',
    role: 'Bron strategiyasi mutaxassisi',
    image: 'https://i.pravatar.cc/900?img=41',
    bio: 'Sofia mavsumiy talabni kuzatadi va booking oqimlarini optimal rejalashtirib beradi.',
    experience: '5 yil',
    specialty: 'Bron rejalashtirish',
    quote: 'Oldindan to‘g‘ri rejalash premium xizmatning doimiy bo‘lib turishini ta’minlaydi.',
    email: 'sofia@drivora.com',
    credentials: ['Bron rejalashtirish', 'Jadval tizimlari', 'Erkin ingliz tili'],
    education: 'Bron tizimlari va talabni oldindan rejalash bo‘yicha kuchli amaliy tajribaga ega.',
    awards: 'Yuqori mavsum rejalashtirishi va bron aniqligi bo‘yicha alohida e’tirofga sazovor.',
  },
  {
    id: 'liam-hart',
    name: 'Liam Hart',
    role: 'Logistika koordinatori',
    image: 'https://i.pravatar.cc/900?img=68',
    bio: 'Liam delivery, relocation va city-to-city handover jarayonlarini tez va aniq boshqaradi.',
    experience: '7 yil',
    specialty: 'Avto logistika',
    quote: 'Logistikadagi aniqlik ham jamoa, ham mijoz vaqtini tejaydi.',
    email: 'liam@drivora.com',
    credentials: ['Logistika koordinatori', 'Dispetcher nazorati', 'B toifa haydovchilik guvohnomasi'],
    education: 'Yo‘nalish tuzish, dispatch va mashina topshirish logistikasini rejalash bo‘yicha tajribaga ega.',
    awards: 'Yetkazib berish aniqligi va shaharlararo topshirish sifati uchun e’tirof etilgan.',
  },
  {
    id: 'nora-blake',
    name: 'Nora Blake',
    role: 'Mijoz muvaffaqiyati rahbari',
    image: 'https://i.pravatar.cc/900?img=49',
    bio: 'Nora repeat clients bilan ishlaydi, feedback yig‘adi va xizmat sifatini muntazam yaxshilaydi.',
    experience: '8 yil',
    specialty: 'Mijozni ushlab qolish',
    quote: 'Odamlar xizmatga ikkilanmasdan ishonsa, doimiy mijozlar soni ham oshadi.',
    email: 'nora@drivora.com',
    credentials: ['Retention yetakchisi', 'Mijoz muvaffaqiyati', 'Yaxshi ingliz tili'],
    education: 'Mijoz muvaffaqiyati tizimlari va uzoq muddatli premium aloqalarni boshqarish bo‘yicha tajribaga ega.',
    awards: 'Mijozni ushlab qolish va xizmat sifatini oshirish bo‘yicha e’tirofga ega.',
  },
  {
    id: 'ethan-scott',
    name: 'Ethan Scott',
    role: 'Park sifati menejeri',
    image: 'https://i.pravatar.cc/900?img=22',
    bio: 'Ethan har bir avtomobilning estetik holati, tozaligi va premium standartlarga mosligini tekshiradi.',
    experience: '9 yil',
    specialty: 'Park sifati',
    quote: 'Avtomobilning o‘zi ham brend berayotgan va’dani aks ettirib turishi kerak.',
    email: 'ethan@drivora.com',
    credentials: ['Park sifati', 'Tekshiruv rahbari', 'B toifa haydovchilik guvohnomasi'],
    education: 'Premium parklar bo‘yicha mashina sifati va ko‘rinish standartlarini nazorat qilish tajribasiga ega.',
    awards: 'Park ko‘rinishi va sifat talablariga mos ishlash bo‘yicha mukofot olgan.',
  },
]
